### ISSUE TITLE
Pip not working

### ISSUE THREAD

**Issue by PhoenixTwoFive** [qpython-android/qpython3#1]
When trying to install a package with pip via pip_console.py, it hangs.
Pip log:
```
------------------------------------------------------------
/data/data/org.qpython.qpy3/files/bin/pip run on Tue Aug  9 11:23:21 2016
Downloading/unpacking requests

  Getting page http://pypi.python.org/simple/requests
  Could not fetch URL http://pypi.python.org/simple/requests: HTTP Error 301: Moved Permanently - Redirection to url '/simple/requests/' is not allowed
  Will skip URL http://pypi.python.org/simple/requests when looking for download links for requests
  Getting page http://pypi.python.org/simple/
Operation cancelled by user

Exception information:
Traceback (most recent call last):
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/basecommand.py", line 107, in main
    status = self.run(options, args)
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/commands/install.py", line 256, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/req.py", line 1011, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/index.py", line 104, in find_requirement
    url_name = self._find_url_name(Link(self.index_urls[0]), url_name, req) or req.url_name
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/index.py", line 209, in _find_url_name
    for link in page.links:
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/index.py", line 530, in links
    url = self.clean_link(urlparse.urljoin(self.base_url, url))
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/python32.zip/urllib/parse.py", line 427, in urljoin
    segments = bpath.split('/')[:-1] + path.split('/')
KeyboardInterrupt
```
If i am guessing correctly, this might be due to pypi.python.org redirecting all traffic to https

**Comment by riverfor** [comment]
We have fixed it in newest version https://play.google.com/store/apps/details?id=org.qpython.qpy3

**Comment by FeanMayocTheHacker** [comment]
When I type in 
 pip install <module>

I get:
 File <stdin>,line 1
  pip install <module>
                  ^
syntaxError:invalid syntax
