### ISSUE TITLE
Pip error

### ISSUE THREAD

**Issue by dexofan23** [qpython-android/qpython3#16]
Error on last 3.6.1 release. Previously I install requests with it submodules
/data/user/0/org.qpython.qpy3/files/bin/qpython-android5.sh "/storage/emulated/0/qpython/scripts3/.last_tmp.py" && exit
ed/0/qpython/scripts3/.last_tmp.py" && exit    <
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/data/user/0/org.qpython.qpy3/files/lib/python36.zip/_bootlocale.py", line 20, in getpreferredencoding
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/data/user/0/org.qpython.qpy3/files/lib/python36.zip/locale.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/data/user/0/org.qpython.qpy3/files/lib/python36.zip/re.py", line 142, in <module>
AttributeError: module 'enum' has no attribute 'IntFlag'
Aborted

**Comment by nagayev** [comment]
@fadedDexofan same problem.
try to install enum34 before
