### ISSUE TITLE
Can't import ctypes

### ISSUE THREAD

**Issue by haxwithaxe** [qpython-android/qpython3#26]
Running the beta via the play store on a stock nexus 6, build n8i11b.
The last line of traceback is the cause for this report
some googling suggest a signature mismatch
https://github.com/kivy/python-for-android/issues/301

```
/data/user/0/org.qpython.qpy3/files/bin/qpython-android5.sh && exit
/bin/qpython-android5.sh && exit               <
Python 3.6.1 (default, Jul 28 2017, 04:42:49)
[GCC 4.9.x 20150123 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
WARNING: linker: /data/data/org.qpython.qpy3/files/lib/libreadline.so.7: unused DT entry: type 0xf arg 0x3ab4
>>> import youtube_dl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/youtube_dl/__init__.py", line 15, in <module>
    from .options import (
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/youtube_dl/options.py", line 8, in <module>
    from .downloader.external import list_external_downloaders
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/youtube_dl/downloader/__init__.py", line 3, in <module>
    from .common import FileDownloader
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/youtube_dl/downloader/common.py", line 10, in <module>
    from ..utils import (
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/youtube_dl/utils.py", line 11, in <module>
    import ctypes
  File "/data/user/0/org.qpython.qpy3/files/lib/python36.zip/ctypes/__init__.py", line 7, in <module>
ModuleNotFoundError: No module named '_ctypes'
>>>
```

**Comment by windyyang** [comment]
Me too. The reason is that there was no _ctypes library in version 1.2.0-beta-3. But  1.3.0 has it, you can update.  But 1.3.0 use python3.2 by default.
