### ISSUE TITLE
pip install requests fails

### ISSUE THREAD

**Issue by rarrr** [qpython-android/qpython3#28]
`/data/user/0/org.qpython.qpy3/files/bin/qpython-android5.sh "/storage/emulated/0/qpython/scripts3/pip_console.py" && exit
d/0/qpython/scripts3/pip_console.py" && exit   <
Input pip commands, ie: pip install {module}
-->pip install requests
Downloading/unpacking requests
  Running setup.py egg_info for package requests
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/storage/emulated/0/qpython/cache/pip-build/requests/setup.py", line 55, in <module>
        exec(f.read(), about)
      File "<string>", line 14
        __cake__ = u'\u2728 \U0001f370 \u2728'
                                             ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/storage/emulated/0/qpython/cache/pip-build/requests/setup.py", line 55, in <module>

    exec(f.read(), about)

  File "<string>", line 14

    __cake__ = u'\u2728 \U0001f370 \u2728'

                                         ^

SyntaxError: invalid syntax

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /storage/emulated/0/qpython/cache/pip-build/requests
Storing complete log in /sdcard/qpython/.pip/pip.log
-->`

**Comment by frodo821** [comment]
```
Input pip commands, ie: pip install {module}
-->pip install requests
Downloading/unpacking requests
  Real name of requirement requests is requests
  Downloading requests-2.18.4.tar.gz (126kB): 126kB downloaded
  Running setup.py egg_info for package requests
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/storage/emulated/0/qpython/cache/pip-build/requests/setup.py", line 55, in <module>
        exec(f.read(), about)
      File "<string>", line 14
        __cake__ = u'\u2728 \U0001f370 \u2728'
                                             ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/storage/emulated/0/qpython/cache/pip-build/requests/setup.py", line 55, in <module>

    exec(f.read(), about)

  File "<string>", line 14

    __cake__ = u'\u2728 \U0001f370 \u2728'

                                         ^

SyntaxError: invalid syntax

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /storage/emulated/0/qpython/cache/pip-build/requests
Storing complete log in /sdcard/qpython/.pip/pip.log
--> ```

QPython can't use unicode string literal. Please update qpython version 3.3 or later, or fix requests library for qpython!

**Comment by rah606** [comment]
I have the same error. Still no solution?

**Comment by frodo821** [comment]
I resolved this error. use pip to create cache and fix the error myself.
Do I have to publish the fixed library?

**Comment by rah606** [comment]
Hello,

For me - of course, this will help many people.

25.01.2018 13:25 "frodo821" <notifications@github.com> napisał(a):

**Comment by frodo821** [comment]
I published just now! You can use this under LGPL 3.0 License.
[requests for qpython](https://github.com/frodo821/requests-for-qpython/tree/master)

**Comment by rah606** [comment]
It works perfectly! Thnx!

2018-01-25 13:57 GMT+01:00 frodo821 <notifications@github.com>:

**Comment by ymongo** [comment]
Works like a charm, 

Thanks a lot!!!!

**Comment by robinchatterjee** [comment]
you can also switch to the python 3.6 beta version.

**Comment by mrachuta** [comment]
For all intrested in topic: I installed Beaufitul Soup 4 via Termux on Android (Python 3.6), and after this I copied them to Qpython3 (Python 3.6) - works perfectly. Maybe this solution could be implemented for other issues with package installation?

**Comment by Adesuaayo** [comment]
> For all intrested in topic: I installed Beaufitul Soup 4 via Termux on Android (Python 3.6), and after this I copied them to Qpython3 (Python 3.6) - works perfectly. Maybe this solution could be implemented for other issues with package installation?

Can please share it
